# Generated by Django 4.0.4 on 2022-05-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_caja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
